//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreciousUI.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreciousUI.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find {0} to close..
        /// </summary>
        internal static string CloseAppFailedMessage {
            get {
                return ResourceManager.GetString("CloseAppFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has closed..
        /// </summary>
        internal static string CloseAppSucessMessage {
            get {
                return ResourceManager.GetString("CloseAppSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t define {0}..
        /// </summary>
        internal static string DefineWordFailedMessage {
            get {
                return ResourceManager.GetString("DefineWordFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string DefineWordSucessMessage {
            get {
                return ResourceManager.GetString("DefineWordSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string EvaluateErrorMessage {
            get {
                return ResourceManager.GetString("EvaluateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get connected first before I can help. Thank you!.
        /// </summary>
        internal static string NoInternetAccessMessage {
            get {
                return ResourceManager.GetString("NoInternetAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find {0} to open..
        /// </summary>
        internal static string OpenAppFailedMessage {
            get {
                return ResourceManager.GetString("OpenAppFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}....
        /// </summary>
        internal static string OpenAppSucessMessage {
            get {
                return ResourceManager.GetString("OpenAppSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find {0} from the bible..
        /// </summary>
        internal static string OpenBibleFailedMessage {
            get {
                return ResourceManager.GetString("OpenBibleFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string OpenBibleSucessMessage {
            get {
                return ResourceManager.GetString("OpenBibleSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play {0}..
        /// </summary>
        internal static string PlayMediaFailedMessage {
            get {
                return ResourceManager.GetString("PlayMediaFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0}....
        /// </summary>
        internal static string PlayMediaSucessMessage {
            get {
                return ResourceManager.GetString("PlayMediaSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results was found from {0}..
        /// </summary>
        internal static string SearchAppFailedMessage {
            get {
                return ResourceManager.GetString("SearchAppFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results was found from {0}..
        /// </summary>
        internal static string SearchAppSucessMessage {
            get {
                return ResourceManager.GetString("SearchAppSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing map....
        /// </summary>
        internal static string ShowMapSucessMessage {
            get {
                return ResourceManager.GetString("ShowMapSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to hypenate {0}..
        /// </summary>
        internal static string SpellCheckFailedMessage {
            get {
                return ResourceManager.GetString("SpellCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hypenated word is {0}..
        /// </summary>
        internal static string SpellCheckSucessMessage {
            get {
                return ResourceManager.GetString("SpellCheckSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop {0}..
        /// </summary>
        internal static string StopMediaFailedMessage {
            get {
                return ResourceManager.GetString("StopMediaFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has Stopped..
        /// </summary>
        internal static string StopMediaSucessMessage {
            get {
                return ResourceManager.GetString("StopMediaSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any suggestions of {0}..
        /// </summary>
        internal static string SuggestionsWordFailedMessage {
            get {
                return ResourceManager.GetString("SuggestionsWordFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suggestions are {0}..
        /// </summary>
        internal static string SuggestionsWordSucessMessage {
            get {
                return ResourceManager.GetString("SuggestionsWordSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any synonyms of {0}..
        /// </summary>
        internal static string SynonymsWordFailedMessage {
            get {
                return ResourceManager.GetString("SynonymsWordFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synonyms are {0}..
        /// </summary>
        internal static string SynonymsWordSucessMessage {
            get {
                return ResourceManager.GetString("SynonymsWordSucessMessage", resourceCulture);
            }
        }
    }
}
